omniauth:
	facebook:
	    key: 
	    secret: 
	twitter:
	    key: 
	    secret: 
	google:
	    key: 
	    secret: 
	windowslive:
	    key: 
	    secret: 
	linkedin:
	    key: 
	    secret: 

collegemapper:
	development:
	  host: 
	  api_key: 
	production:
	  host: 
	  api_key: 
	
exceptional:
	api_key: 
	
google_analytics:
	account_id: 
	
