
common: &default_settings
  license_key: ''
  app_name: ''
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: true
  capture_params: false

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
